image: ubuntu:rolling

variables:
  BINARY: "dist/glone"

stages:
  - build
  - release


# =================== build===================

build:
  image: ubuntu:rolling

  stage: build

  before_script:
    - apt update && apt upgrade -y
    - apt install -y python3 python3-pip python3-venv
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt

  script:
    - ./build.sh

  artifacts:
    paths:
      - $BINARY

  only:
    - web
    - tags


# ================== publish ==================

release:
  image: ubuntu:rolling
  stage: release
  needs: ["build"]

  before_script:
    - apt update && apt upgrade -y
    - apt install -y curl

  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "$BINARY" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Glone/${CI_COMMIT_REF_NAME}/glone_${CI_COMMIT_REF_NAME}"'

  only:
    - web
    - tags
