defaults:
  groups:
    excludes: list

  repos:
    protocol: ssh | https
    clone: bool
    tasks: list


auth:
  - id: str
    name: str
    server: str
    user: str
    token: str
    config: str # multi-line


remotes:
  - id: str
    name: str
    url: str
    auth: auth
    type: gitlab | github

    starred_only: bool
    owned_only: bool
    excludes: list

    defaults:
      groups:
        excludes: list

      repos:
        protocol: ssh | https
        clone: bool
        tasks: list

    groups:
      - id: str
        name: str
        source: str
        dest: str # optional: will tak source
        excludes: list
        defaults:
          protocol: ssh | https
          clone: bool
          tasks: list


repos:
  - id: str
    name: str
    source: str
    dest: str # optional: will take source
    clone: bool
    tasks: list
